# Generated by Django 2.2 on 2019-04-26 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('author', models.CharField(max_length=255)),
                ('data', models.CharField(max_length=255)),
                ('price', models.CharField(max_length=255)),
                ('rate', models.CharField(max_length=255)),
                ('comments', models.CharField(max_length=255)),
            ],
        ),
    ]
